"""
titandash.py

Consolidate and put any functionality used or required by the gui here.

The gui is used to begin the server process. And a system tray icon is initialized
with a menu inside tha can be used to restart, stop or migrate the server.
"""
import PySimpleGUIWx as sg
import os
import sys
import subprocess
import webbrowser

import win32gui
import win32con

# Hiding the python window if specified.
if '--hide' in sys.argv:
    program = win32gui.GetForegroundWindow()
    win32gui.ShowWindow(program, win32con.SW_HIDE)


# Default environment variable to ensure proper settings are used.
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "titanbot.settings")


class TitandashTrayApp(object):
    """
    Encapsulate all system tray application functionality into a class instance.
    """
    # Generic
    TITANDASH = "Titandash 1.5.0"
    START_SERVER = "Start"
    STOP_SERVER = "Stop"
    STATIC = "Collect"
    OPEN_DATABASE = "Open"
    MIGRATE = "Migrate"
    GITHUB = "Github"
    EXIT = "Exit"
    ACTIVATED = "__ACTIVATED__"
    DASHBOARD_URL = "http://localhost:8000"
    GITHUB_URL = "https://github.com/becurrie/titandash"
    ICON_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAAQQAAAEECAYAAADOCEoKAAAACXBIWXMAAAsTAAALEwEAmpwYAAA57mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMwNjcgNzkuMTU3NzQ3LCAyMDE1LzAzLzMwLTIzOjQwOjQyICAgICAgICAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIKICAgICAgICAgICAgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIgogICAgICAgICAgICB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIKICAgICAgICAgICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOmV4aWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vZXhpZi8xLjAvIj4KICAgICAgICAgPHhtcDpDcmVhdG9yVG9vbD5BZG9iZSBQaG90b3Nob3AgQ0MgMjAxNSAoV2luZG93cyk8L3htcDpDcmVhdG9yVG9vbD4KICAgICAgICAgPHhtcDpDcmVhdGVEYXRlPjIwMTktMDktMTRUMTE6Mjg6MDMtMDM6MDA8L3htcDpDcmVhdGVEYXRlPgogICAgICAgICA8eG1wOk1vZGlmeURhdGU+MjAxOS0wOS0xNFQxMToyOTo1My0wMzowMDwveG1wOk1vZGlmeURhdGU+CiAgICAgICAgIDx4bXA6TWV0YWRhdGFEYXRlPjIwMTktMDktMTRUMTE6Mjk6NTMtMDM6MDA8L3htcDpNZXRhZGF0YURhdGU+CiAgICAgICAgIDxkYzpmb3JtYXQ+aW1hZ2UvcG5nPC9kYzpmb3JtYXQ+CiAgICAgICAgIDxwaG90b3Nob3A6Q29sb3JNb2RlPjM8L3Bob3Rvc2hvcDpDb2xvck1vZGU+CiAgICAgICAgIDx4bXBNTTpJbnN0YW5jZUlEPnhtcC5paWQ6N2Q2MmI1NTQtMTZjZS1iNTQ2LWE5NWItNWJjOWQ2ZGI0MmQ4PC94bXBNTTpJbnN0YW5jZUlEPgogICAgICAgICA8eG1wTU06RG9jdW1lbnRJRD5hZG9iZTpkb2NpZDpwaG90b3Nob3A6MTdiMTc4MWEtZDZmYy0xMWU5LWIxZGYtOWM3YWQ2YzJlZjg0PC94bXBNTTpEb2N1bWVudElEPgogICAgICAgICA8eG1wTU06T3JpZ2luYWxEb2N1bWVudElEPnhtcC5kaWQ6ZjdiN2QyMjEtMmU0ZS1jMDQyLTk1MzEtNDE1NTUwZTM0NGVjPC94bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ+CiAgICAgICAgIDx4bXBNTTpIaXN0b3J5PgogICAgICAgICAgICA8cmRmOlNlcT4KICAgICAgICAgICAgICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDphY3Rpb24+Y3JlYXRlZDwvc3RFdnQ6YWN0aW9uPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6aW5zdGFuY2VJRD54bXAuaWlkOmY3YjdkMjIxLTJlNGUtYzA0Mi05NTMxLTQxNTU1MGUzNDRlYzwvc3RFdnQ6aW5zdGFuY2VJRD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OndoZW4+MjAxOS0wOS0xNFQxMToyODowMy0wMzowMDwvc3RFdnQ6d2hlbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OnNvZnR3YXJlQWdlbnQ+QWRvYmUgUGhvdG9zaG9wIENDIDIwMTUgKFdpbmRvd3MpPC9zdEV2dDpzb2Z0d2FyZUFnZW50PgogICAgICAgICAgICAgICA8L3JkZjpsaT4KICAgICAgICAgICAgICAgPHJkZjpsaSByZGY6cGFyc2VUeXBlPSJSZXNvdXJjZSI+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDphY3Rpb24+c2F2ZWQ8L3N0RXZ0OmFjdGlvbj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0Omluc3RhbmNlSUQ+eG1wLmlpZDo3ZDYyYjU1NC0xNmNlLWI1NDYtYTk1Yi01YmM5ZDZkYjQyZDg8L3N0RXZ0Omluc3RhbmNlSUQ+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDp3aGVuPjIwMTktMDktMTRUMTE6Mjk6NTMtMDM6MDA8L3N0RXZ0OndoZW4+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDpzb2Z0d2FyZUFnZW50PkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE1IChXaW5kb3dzKTwvc3RFdnQ6c29mdHdhcmVBZ2VudD4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmNoYW5nZWQ+Lzwvc3RFdnQ6Y2hhbmdlZD4KICAgICAgICAgICAgICAgPC9yZGY6bGk+CiAgICAgICAgICAgIDwvcmRmOlNlcT4KICAgICAgICAgPC94bXBNTTpIaXN0b3J5PgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICAgICA8dGlmZjpYUmVzb2x1dGlvbj43MjAwMDAvMTAwMDA8L3RpZmY6WFJlc29sdXRpb24+CiAgICAgICAgIDx0aWZmOllSZXNvbHV0aW9uPjcyMDAwMC8xMDAwMDwvdGlmZjpZUmVzb2x1dGlvbj4KICAgICAgICAgPHRpZmY6UmVzb2x1dGlvblVuaXQ+MjwvdGlmZjpSZXNvbHV0aW9uVW5pdD4KICAgICAgICAgPGV4aWY6Q29sb3JTcGFjZT42NTUzNTwvZXhpZjpDb2xvclNwYWNlPgogICAgICAgICA8ZXhpZjpQaXhlbFhEaW1lbnNpb24+MjYwPC9leGlmOlBpeGVsWERpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjI2MDwvZXhpZjpQaXhlbFlEaW1lbnNpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo8P3hwYWNrZXQgZW5kPSJ3Ij8+LMWZfwAAACBjSFJNAAB6JQAAgIMAAPn/AACA6QAAdTAAAOpgAAA6mAAAF2+SX8VGAAAbhklEQVR42uydW4wkV3nH/985denLzHTP7M276xu2A8LE2NgYiECKEIgYKYQEUKQkykMSCSkJEBElQsoDiZTkLUHKU5SHKJFClIRECigSCAkSiIJAYDB3w3rtXbC9u7Pr3dmdS1+q6pwvD9W9M7u2e2bnnIXe7v9Panktt89WnTr16++cqvqXqCoIIQQADLuAEEIhEEIoBEIIhUAIoRAIIRQCIYRCIIRQCIQQCoEQQiEQQigEQgiFQAj5CZLM0s70/unfZv+I2QT+/IU/G/zXZ/8ARsLb8wppNtD+vd96nzSbn4f3ge15yPIypNnY9as6HALOATJhP0SggwF07crk793Ir+CBZSBNgUgP9mWvfx2FMI341QtzoPAE/vkzrfLb3+vCRijwnIcstKGbWwlEAOeDZGC6HZh2C7B2dyEUBX+SKYSb+etpZ/+IWQskiZcsQzQhZBlgjEJk/7/C3sOsLEO6nfqXl4/Vcw2BzCnewyx3IctdioBCIPMuAxnLIHT9gVAI5NaXgaEMKARCGVAGFAIhlMEMk7ALyI3KwHDNgBUCIZQBhUAIZUAhEEIZUAiEvIQMeJ8BhUAIryZQCIRQBhQCIZQBAe9DIDtRcAGRQpilAa3RQjTmUwhTKoPxY9mxji3HyHwIwR4/Cvfc8wBm+IB7D3gvqCpA4+QhoKoAr5VZWYYsLdV/x0/ipNmrdFTvhmoHQAxLWaieA3COp/+MC8EcWIFWFXRzCzBmNp/NTxJIpyPm+NF6H2OsFzRzmIMrx2Rl5Q5UlYRFs4nASB/A+YlSsRb+3Hm4Uz8CkpcfhpKmKE88/deDz3zuPZKlPsL+mub7funPzaFDH4WrohwSRqhNa8XrHEy3Axw6CGk16ySg8VRiZqxnoK+482PSbn48yq+4V5iFdrP3z//xier7P+wiTcMaHQwlf+xtX2i84+ffpf3hRCHo5ha0P5gstiyHXl4X//xZSJ6ZCEKAbmyKttt1ZURmeA1hfPIXBbQooGkKaTYheVpPI2ZBDKqA13Nw/lywEFSBNIW0W4l/9kxe/uDEkuR5WJO9PtLXvXZRi7IOUZ0ktrKsZTBJCEYAaxRJMrGSuKFpijG6699LIcwQ4xOlLKFlORJDo64YRBjzNZZBksAstAFBA4n1kmXbVdV+qRyQWLfrImDMRUJCIexXDKbZAOZdDGMZLC6M+oEnApkHIbyEGHxZ1mVyswHJs9mZStzgNMEstFgtkTkVwstWDMlojSHfPllmXgajacI87C+hEG5MDBW03ICmg9lfY1CFJAlkYYGjnlAIe6kYkKbALIpBFZKmkHFlQAiFsLsYtCxrOYzXGNJ0+hbcROtLZ7u9E/G6NQPKgFAI+60Yqgr+7CqyN7+xvtFpqrYRgPNIHrh/b993DuVXn4C/cKGugAihEPYhBq3fijytv6x2aXHP3zWPLWP4mc/BXbgIySgFMmGssAt2KbdnwW/NBvJ3vh3m8EFoUfK4Egph7oueZgONd74N9vDBeq2EEAphzqXQqCsFe4iVAqEQCABp5MhZKRAKgVxTKTz2tlGlULBDCIUw91JojqRw+BCnD+QqvOw4UZdm5qXQ+MVfwPAL/zfQYaFalICE7bMWZf0ItOrkqzTj/76X7zlv6uyEGIEwHvDe7Pr3UgjkRWOx34cOW9O3YV6PalEcRoT7KMUYTR95sJ28+r4MvqwfDQ9hMIS986iVZmPynZTWQIZDSLs9UbySpTAHVwbJz9w7kCzVCEIQ6XaG0m7V4iIUwl6rg+Fn/6deeJumzIDEwp87/6H+v3/qI7AxMhUVZrmryWu7kJXLgA0bEtoYAq0tIK0AP2EqYgSmbaGNxq6//Mkr7/3wwivv/SjihKwaABfrhjn8KYQbLC+1NwBcNT3pPkkCvXLF+DOrEkcIHhgOxR8vvD93BkjC7mTUQR+6cdnBVUC1y4JlbiC5gfar3aRwDiLxUpI5VaAQ9oW1kFYTurU1PUIwBrBWkSaIJoQkURgL2NEnsM+21yF26TMjkG4L2l/nSTwthTG7YPIglCyFWMsBeXPWQiALOaSZAp79SyHcCogAjZz9cNP6F5DlJvuBQriVqoSsXoBilXBz+redQdp5XSWwjymEW6FKCH1fAZlAIZDFDsyBbh18y3sEfmpwUfEG1hJ0aOt3IZJo0wUMAR2iToIavRdChgW014MOi+1pG6EQpq9KaEzXFYdbXQYFoEPZvhgxrgryrK4UigK61QcmvQFqn4LnuygoBFYJU1cZyEtfmRyJYeebpHQwQKy3epvF9ugGLFqBQmCV8FOXgQ4FGO7h/B6LoRX3KoR0lup8Sa5TUAhxqoSkTj0mN08GLyrxI5689QNOFMJLVU/sghuvEkwj52D6ScmAUAjTXiUgTYHEcgp6Q2sGlAGFMNNrCTlohL3KYHxpkd1BIczsWgLvXty7DIQyoBDmoErgMw6UwYzBqwyBVYImQ6DaQ15CrEpivOLufZwTzfvtZwjU15/Q9kQqmAYgCmmETxUky+JWYklSP6bN6o5CiF5iNRrQ4WByFqF6SLMJNBv1CRNyhlgLEdHsDQ8DxvgYgpHFttp72zCLbQ8TOCRcCWl2X1V88fGP1WlTEfp4ZTn1l9biJMGqpumrX/kZtFuf5iPXFEL0KgFGRqEgE0a+R307bpLAPX827KamJIE/c1aKr38LsBFSYL2HWVlWNV11p39gQhOT4Cv4y/6u4gs//LCWwyg3cCX3vxLV90/EOWbeo/07v9EzR2/7NKoqTpvveCuFQG58IEq3A+s93NnVq+sQwVOHWFMQaJw2a0k6aeQWFlGEIFkWb72mTogacsrwMtUYu+CnIIXbjoxOHnYJoRAoheUOzNEjNALhlIGM5u3LnfqPZ1brhTc+LEVYIcwxrpaCOXakLhQ4nyUUAqVglruwx8ZrCpQCoRDmXAoOstyBPUopEAqBjCoFSoFQCOQ6KXQpBUIhkB3Thy4rBUIhkDGjm5fMWAqE/AThfQhTKgXep0BYIZAd04cd9ylw+kAoBHL1PgWuKRAKgdRScLz6QLiGQK6XQgcGgL9wkc9EEQphb3uT1AE9oQtwRqDG7O3XeE/fqbdJ0nSUmLQ/7OGDMK0WirOrQy1LiLfhfeY9UFXQ0kGHFeAC+85X0MJB+xW0rMKPhQJaujqmLoYId76khdXWbAvBn119v25stGFM2JFWtZJlJyXPP6W7DRqR+i1Okwa+CLQoHqmeOf1WqAbF9Ii1apY7b87e9IhCjMY4QcziApJHW+rva3kYG97egbvUHmt7uAiJRAaQ7HZUCwtxJrjqjTlyWE1nKcrbt3TG3uA1U0Lof/wTf1U8/sRi/c6EgIPc66P5a+/9SvNX3/0p3epNPtF7/fqXZoIQJE1QnX7uXVt/+/d/utt39zJ9SB64H/75s9CyDL8W6TzM8jLSty+qpE8KJDxCzRxR1eYzBi7Cyxgyhf+OQ/ntZyBZnAohfegBQZoiOELNOZgjhymEqcWYTRiziNCoQWMAkV7UklJQYDwNiRCdpoNhXZJHEIIWBbQooYMhID5YCDqsoL0CUYRQ6WjbijqbMsaUwbntqUPID0dRwN5xnEKYakTC56036yagcbsh7V9tA3Fi2OX6f5GIDcbayJu1vxGOp/czdfrwsiMhhEIghFAIhBAKgRBCIRBCKARCCIVACKEQCCEUAiGEQiCEUAiEEAqBEEIhEEIoBEIIhUAImRJmKw/Be4Fz4dFYdYBG3FAE1e0sv5A8hHGwR4SAj2va09EnNIVEx3mF4/YkvN90vL+Is7+qnqf+HAhBFtpGuh1IFhahhiyDNBujRidnJV7zmUSailnu1gMyUAiytAjpdiBVjMQkhXSWIPkixHUBBEaoaQXJ25BGB3AFYkSoSWsRZrkTnO4GAdQrpNloS5atwAYWyCJAkpQANiiEKWThT/7wXSiGWYTwUaNVdQFVBWm3JnzLAMNiT2HAkiZGYgih8rBHF2G6C9AiQsCneshCW6W1APHLgAQOCe8g2aJIswu4Mnz7UsAePwyzvBbsKgAwWQZ37sIHB5//3/dLEravutUD0vS/87e88VcohGmsEFrNryLP4kSobW1Bqwkx4qO0ZX9lfU9x3trrO/fUMwDCpgy+cDCHEmj/FLSIUCF4D+ksw19eUb/+dJSQVckW1F86hVghq7h0BNWJU5BG+LRNmg2YdjMvv/P9XNKwfdX1TeRvW13klGF61xB2j0TfqxD87vHremW9Tu7dS6irCJAmwWsIogJYC9gEiPBaBoiv2zIWMEl4hQBst6UuXAhG6/bSJHy0qgJJUr+/I8sQKgTkGZDYmcph51WGfQpDq6quDgy7kFAIFMLldSBGDDohFMItTlXW04WbFddOCIVwa1QGMAZ+XB1QCGTG4Nuf9yoCoH4palFAFNDE1AuPlAJhhTBHIpCRCLZ69XXnsgLyDKbbBfb6hmhCKIRbXQYjEfT6tQjG9ySI1BLIU5huh1IgFMI8VAaSpNDeYHut4PqpgVcgSyGUAqEQZlgExkCM2X656KQ1AlVIxkqBUAgzLIIbXCTUulIw3SXACKVAKIS5FMGLpJBx+kAohFtWBNaGi+BF04eM0wdCIdySFcHN4Or0ocPpA6EQZn5qcENS6LJSIBTC3IrgeinsuE+BTiC3CsnMimAvsWY3kx33KejmFqCqdT5goB3GbcRoa2d72PkJajBiW9huQzXCpul2O7GOBYUwxR4wBlESk1CHmUirGb5NrSbQWYJfPe+l0bja/P6PmIdkObRoAkmcxCQkDcDmkKSJGIlJdVsNQAyCA1IShdoMsM3wQBhVwDbqcJRmE5IGDv/K1YErFMJ0olfW4S9fufYW4/1gLfza5d8cfu6L74egCh7UImpWunenD9yvWpUa1F7hkT50DHLEQIcxwnoUki+oObQEn4sPTkxSB9O5Q2GsrzMVwxOTzOFltP/o7igTXMkT6KUVpFdeBWSBhun1jT18SCiEKcX3+vAvXKyfPRDZ92CUNIF79szd/U988i2IMfVwHukbHoY7cRK+35f6l3Of51u/gr13HWblBLQfoUJQD9EVxQuH1K1+3yAJrBBcBbhS3cWnDNwgXAgK4PAW1PwgziCxKdxzlzH8yklIMzBkdWMD6c89qhTCNK8ddDtAlkI3tvZ/IlsLpEkprSZiCUGytM7yS9PA1GUZ5RWm4SdbrdF6GJgEsClgImSdX81UjLSNkgA+jTNGfAqY+jhIGlghpCmCo9ynjNm7yuA9pN2GLLZ5yY+QuRcCUN812G5DFhcoBULmXghjKSy0KAVCKITx9EEh7RanD4RQCNdPHygFQiiEnVJYoBQIoRDGUljgQiMhFMI1lQIXGgmhEF4kBU4fCKEQrkqB0wdCKISdUuB9CoRQCFfhfQqEUAicPhDy0vBlr1el0AKg9VOShFAIlIK02wAE2h+wPwiFcOtPgEydZRAQsy5Li5BGDvf82aEWRR0DFiEPQcsK2i+hgzKoPe07oKiAsqj/GSxCDyQlUJZAUQA2cNrkq/p9mGUBVAWi5CFUJer0pQhTOof6Jb5FCVgf1nVFAThHIUztj/zm1mN6+UoWFlohgDXeLHceyh5+sE4KDRaCIrn/brG3JapF2EmiQwf74B0i9zY1SoSaeki2CMm7ag41PEzgkPAOpnuP6qGmh5ZRhGDyuwRprjFCc6VhgbuPS/ZISyUPW0LTXs/Y40cZoTat9P7uH/+leOJbXcnzsIbKCunDD8JfvAQdDIMrBB14JG9YkOThHwG9wPaKCni0geI1a4KiDO808RBxakTEuRcECEwmkgpqDorzl0Q1QoWQAnLyKPyTzwvSCEIoU/hLOdyzZ0SaYYlJurkJf2WdEWpTWyEMhwPtD+oI9KAStYL2+s5fWrM6GEoMIejmFnT9sujWIFgI0l+HFmuIIgR4wABqEtVyTYJTl1FBk02ouyyqQ8TIVNRiA9pfq+Pjgo2QQrdW4C+tIVgIG5vQXp9ThileQ1AYE7SGcHUtwgiuthVaqhqMshlN+JqEmFGD40+UjhuduDHavL6tGBW1xFnLGfefGEQbJyKzdQqBEEIoBEIIhUAIoRAIIRQCIYRCIIRQCIQQCoEQQiEQQigEQgiFQAihEAghFAIhhEIghFAIhJCpYLbyEFS3P7HaiRHNfrWdSNuGnZ/gjXuJT8z2EGcbVSM1p/HHCYUwnUizUb9jIc/CGqoqSN4AkhYkScJDMBIPJA1I2gIyG9heBbENCHJAbIRe8xDJIZJBpIEYiUl1ey0AFsEBKQKIaUCyNqJEqKUJJG/WL+gJTEyCKiTLKIRpxd59p0mHBSQLG9RaOKSP3i7pOxQYhgeFqvdI7roNqh5oFWFCKB3Quh3GKGBdJCEswZiOqO0DkgQLwZgjAskQJVPRAqZ1HHL4VUASIZ0ot8DxY0hfkyI8ZLUPc+SQoRCmlOq7T/rh156ANPLAA13B3NVTe/BJqA4i/Mp5+OEAbvWHQBkhU/GuHpw/O4o5jyAEswLVA+qqH0bJVBTk6txJRMlUBGA2KvgffzVOhdBO4Z66D8MvnYS0AjMV1zeRvuFhTyFM7d4kkCyFpIGDOhPAJIBP6/cWBAeF+rqrbQp4FyYEK6NfcRvp8PlRW+P2YrRpUac3+yhCgIz6zkZoy6Q7xknglCFL6/eAzBC8ykAIoRAIIRQCIYRCIIRQCIQQCoEQQiEQQigEQgiFQAihEAghFAIhhEIghFAIhBAKgRDy02W2Hn92bvsT2o739aPKvkKUx5/9jm0LefzZOUAdgPEnFD9uS4AI+4pq1NZ4+yI8sjzuPx+hLW92HIvQXR2NEwphSsudQwdhj92myMICUjCoYLoHYJaOqaZFFCHIwkFIuQ5Uw/CAlMbBOjHJVFGEIKajIgsw5jAgoSkklYpZUaNbGiUxyQCSLcMsHY0zWpspzPIh2GNbQCMwIGVpS0xniUKYVqSRQ1pNIMvCki+NA7IcSFqKNAkf1JUHbm+Kf2tXUYamCHmYpC1SbiokUoQarDSa7/2ASOPLdcWw7yMAwKpzz/72sP/cB0QaGqNCEJOLpk2NMVolTYEsF2k1FY3AGbN6QWgYD4VwE2cMP34O5YmnRfJG0CjUfonkkYaTQyeMbkWIASsd0F+Ek9OC4Eg2B2gCV50elfgxKoQ2AP0eYJ8I2zaB6gCqV37k3DMCGIlRIdhBB/6Fk4IsglxaGfw5qcdJM2z468YG/IUXKITp3ZsEkqaQNHC3KgA2qeO2bIQYMG/qhGQdR5SFnXRAMkpHlihCqOPOkIdFpwtUN6Baou648fbFiFCzdYSaiRGhlgB2PE4C489SRqgR8jIy2IRqP5KkCIVAKANCIRDKgFAIhDIgFAKhDAiFQCgDQiGQ2YMyoBAIGVUGJVR7lAGFQMi2GAiFQAihEAghFAIhhEIghFAIhBBCIRBCrmW28hBUAT/6hOAVEAVSX3+CL7U5wHjU2QOh7XkAFVS3ECdTcZx76JLt7XspBHtPU9Id+xkjw2B0HNIIbWUeqAro5hbgAyPUNregRdGiEKYUe89dJu33gSwLa6ioYDv3iVzsAsPwXEAtPExxD9LsABCYM6gokaQPnsobv/xp1TJChacQScTaO09NHg51GpL3uwnNwpgDJk0fjSOEDDDVPdA1QYzEJKwrsje98evpz77vy9DKBm3fsDDpow99l0KYUtzpZ335g6cgeWDIalVBmk2tnnwGOggMRQWgmx6NrkLfeBJahkWoqW4hSR/8Wt541wfqKiFKaVVXV5N1C9XnoLq5y0wzgfeXfFl+I5oQ/PcEg7/5NrAQLgStKix86HX/2XjP2/9SFtp1cvK+izUPs9TmlGGqpwy6l8G9h3bGUwbng4WA1ANmHE+m4ScvqkS1N7qNOA6CbOJ/BQZw7swNnOAa77gajTZlEAvo1mZefPFLSB96ALLcBap9ZlM6D21kM3UKcVGR7GUyBu/PAwgNiJ2W3THQokT5+Deha5eBJOEhphDIXmsHYAjnzgGYoUBRa6FFieLxJygFCoHMbXVwXaWAokLx+DfhKQUKgdxIdTCjQ8UaoCg4faAQyF6GR10dDGd7qFgLlFxToBDIxOpAtZjt6uCaM8FAy3pNwa+tza0UKATyskNDdVwdzEkoijFAWaGc4zUFCoG8zNrBHFUH10uhqFA+/gT00vxJgUIgE9YOZvDKwp7WFLYrhXlbU6AQyITqwM5vN4zXFL42X/cpUAjkRUPCudX5WjvYpVKYp4VGCoG8qDpQXeXQ2CmF0W3O87DQyKNOdo5+eL8KVVYH13aLBcoK1RxMHygEsqM6GMJ7Vgcvu6ZQ1dMHvTS70wceeXJ1KHh/ntXBLlJAWaH4+jfhL60B6exJYbb2qKysFkV4fkFVAVVlUFZAWYUHpJQe8A4wFSBV4AlXAuLjnrM6embBnx3ta0iWgY62b7yfgRtqAPgKOiziJCZ5Dzhn4H395/0wKFB+9RtIX/damG6HQphagd95fD3d2GgGR6h55+1dd2TqXFOL8Ag12/Mw3aPQqgQCf4FV+xDXNSh1dCJHILfww4uQEoA0w4SgCUQXxOor4gihAszi0TJ59X19tCRCZJI35sBKXxYXAVcFiaU6+Qzs7UcphGll4Y8/+FY4ZyEhI1ogaaLFV77+++WTJz4ixoRXHA0P/Zqg+mQKbIZFsmkPSH9doO+u/xy+dGCgyQbcd84ApRklOwU0ZxX+PFD960gGodXVoI/2B17/D61P/O5f6GAgUXbY+7UoA65ykCylEKYW1efgAyLPRv9bdfIU3I+evVg99XTdVoQpiCwtojp5Gnr5Sj0X3e8ubm4hv7DmoQJUEWLKLKDP9qEXNuMslCUJ9OKGlt87GaXvtNeDXtlcA/BscJr2eEqjEePdRCiEKRbC/g+21L9o7unT8BfXIEliJU3jCEEESBJIlgB5GiQElGl9bRyIs44gAKzUbZoYkel1W5JH6juXAkZslKxMsqclGzIauO7pU/CrFyCJZZ8QCoEyuABQBoRCoAz86gvM1CMUAmVwGv78C6wMCJlbIYgAgu1pgqUMCAFm7SrDjcjgJCsDQua7QuA0gRAK4VoZjBcQKQNC5lMIvLRICNcQrpHByVPw5y/w0iIhc1shXF1APDVaM6AMCJlPIexcQLzANQNC5lcIOyuD1Rd4nwEhcyuE0dN1vM+AkHkXAu8zICSIGctD8KhOPA0dy8C5/YulcuZqPmOEgBQtS2hRQIsiLCBlWADOxTWdap0vKCZWW9H6TocF4D2fyqUQ9jF41q4AUJijRwJ7xcJ4P0gfeM3l8XpEEM4hue8eSCOHbmwFBZFofwBz6OA6nI8ngySBLLQBE+4ZsRbS7fRj9Z0OBpDO0ta+A1HJjR0/ZQoNIWQm1xAIIRQCIYRCIIRQCIQQCoEQQiEQQigEQgiFQAihEAghFAIhhEIghEwp/z8A+HbL8RdZASUAAAAASUVORK5CYII="

    def __init__(self):
        # Store a boolean to determine if the tray is in a working state.
        # When certain errors occur, we can terminate the while loop with
        # this boolean.
        self.stat = True

        # Main system tray object.
        self.tray = sg.SystemTray(menu=self.menu(server_online=True), tooltip=self.TITANDASH, data_base64=self.ICON_BASE64)
        self.message("Initializing", "Starting %s" % self.TITANDASH)

        # Always make sure the server is killed before attempting to start it again.
        # We don"t want any port conflicts so the server is restarted on start.
        status = self.kill_server()

        # Error occurred while shutting down server.
        if not status:
            self.stat = False
            self.message("Error", "Error Occurred While Terminating Server")
        else:
            self.start_server()
            self.message("Initialized", "Started %s" % self.TITANDASH)

    def message(self, title, message, time=2000):
        """
        Send a message through the system tray icon with some information.
        """
        self.tray.ShowMessage(
            title=title,
            message=message,
            time=time
        )

    def menu(self, server_online):
        return [
            self.TITANDASH,
            [
                self.TITANDASH,
                "---",
                "Server", ["!" + self.START_SERVER if server_online else self.START_SERVER, "!" + self.STOP_SERVER if not server_online else self.STOP_SERVER],
                "Database", [self.OPEN_DATABASE, self.MIGRATE],
                "Static", [self.STATIC],
                self.GITHUB,
                "---",
                self.EXIT
            ]
        ]

    @staticmethod
    def get_server_procs():
        netstat = subprocess.Popen(["netstat", "-a", "-n", "-o"], stdout=subprocess.PIPE)
        try:
            output = subprocess.check_output(["findstr", ":8000"], stdin=netstat.stdout)

        # If no output is returned from server procs call.
        # Safe to assume server has been terminated.
        except subprocess.CalledProcessError:
            return []

        # Parse output.
        output = output.decode().replace("\r", "").split("\n")

        parsed = []
        for line in output:
            line = line.split(" ")
            line = [elem for elem in line if elem != ""]
            line = [l.replace(" ", "") for l in line]

            try:
                if ":8000" in line[1]:
                    parsed.append(line)

            # IndexError may occur when some trailing output is present
            # in the lines available for server processes. We can ignore this.
            except IndexError:
                continue

        return parsed

    def kill_server(self):
        """
        Attempting to kill the server process if one exists. Existing if fails numerous times.
        """
        # On top of killing the server, the external auth reference should also
        # be set to offline.
        subprocess.run((["python", "manage.py", "offline"]))

        # Server termination loop.
        attempts = 0
        while attempts < 25:
            attempts += 1
            procs = self.get_server_procs()

            # Break if server is killed.
            if len(procs) == 0:
                return True
            # If the current server is in a state other than listening,
            # we can assume the server has been killed.
            if procs[0][3] != "LISTENING":
                return True

            pid = procs[0][4]

            # Attempt to kill the server with the pid discovered.
            subprocess.run(["taskkill", "/F", "/PID", pid])

    @staticmethod
    def start_server():
        """
        Send out the process that will start the django server.
        """
        return subprocess.Popen(["python", "manage.py", "runserver", "8000"])

    @staticmethod
    def explore_database():
        """
        Open the database in windows explorer. This may prove useful when looking to backup the database.
        """
        return os.startfile(os.path.dirname(os.path.abspath(__file__)))

    @staticmethod
    def makemigrations():
        """
        Run a makemigrations command in Django.
        """
        return subprocess.check_output(["python", "manage.py", "makemigrations"])

    @staticmethod
    def migrate():
        """
        Run a migrate command in Django.
        """
        output = subprocess.check_output(["python", "manage.py", "migrate"])
        output = output.decode().replace("\r", "").split("\n")

        none = False
        for line in output:
            if "No migrations to apply." in line:
                none = True
                break

        if none:
            return "Migrations Are Upto Date"
        else:
            return "Migrations Successfully Applied"

    @staticmethod
    def collectstatic():
        """
        Run a collect static command and return the amount of files collected.
        """
        output = subprocess.check_output(["python", "manage.py", "collectstatic", "--noinput"])
        return output.decode().replace("\r", "").replace("\n", "").split(" ")[0]

    def start(self):
        """
        Start system tray functionality. The server is started by default before the tray is initialized.
        """
        # Begin event loop. Waiting on actions from user to perform functionality.
        # Server should be running at this point.
        while True:
            event = self.tray.Read()

            # EXIT: Exit titandash application, destroying server in the process.
            if event == self.EXIT:
                self.message("Terminating", "Terminating Server Now")

                # Attempt to kill the server before exit.
                if self.kill_server():
                    self.message("Terminated", "Server Terminated Successfully")
                    self.message("Exiting", "Exiting Now")

                # Break after regardless of success, tearing down app.
                break

            # ACTIVATED: Open up the dashboard system.
            # localhost:8000
            if event in [self.ACTIVATED, self.TITANDASH]:
                webbrowser.open_new_tab(self.DASHBOARD_URL)

            # START_SERVER: Start the backend server.
            if event == self.START_SERVER:
                self.message("Initializing", "Starting %s" % self.TITANDASH)
                self.kill_server()
                self.start_server()
                self.message("Initialized", "Started %s" % self.TITANDASH)

                # Update the tray object so that the menu used disables
                # the ability to start the server if it's already running.
                self.tray.Update(menu=self.menu(server_online=True))

            # STOP_SERVER: Stop the backend server.
            if event == self.STOP_SERVER:
                self.message("Terminating", "Terminating Server Now")
                self.kill_server()
                self.message("Terminated", "Server Terminated Successfully")

                # Update the tray object so that the menu used disabled
                # the ability to stop the server it it's already terminated.
                self.tray.Update(menu=self.menu(server_online=False))

            # OPEN_DATABASE: Open the directory containing the users database in explorer.
            if event == self.OPEN_DATABASE:
                self.explore_database()

            # MIGRATE: Perform a database migration.
            # We also perform a quick makemigrations as well so we are upto date.
            if event == self.MIGRATE:
                self.message("Migrate", "Performing Database Migration Now")
                self.makemigrations()
                migrate = self.migrate()
                self.message("Migrate", migrate)

            if event == self.STATIC:
                self.message("Static Files", "Collecting Static Files Now")
                collected = self.collectstatic()
                self.message("Static Files", "%s Static File(s) Were Collected" % collected)

            # GITHUB: Open up the github repository.
            if event == self.GITHUB:
                webbrowser.open_new_tab(self.GITHUB_URL)


TitandashTrayApp().start()
