# Generated by Django 2.1.7 on 2019-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestige',
            name='time',
            field=models.DurationField(blank=True, help_text='The time/duration of the prestige.', null=True, verbose_name='Duration'),
        ),
    ]
