# Generated by Django 2.1.7 on 2019-08-10 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0003_clan_raid_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='last_prestige',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.Prestige', verbose_name='Last Prestige'),
        ),
    ]
