# Generated by Django 2.1.7 on 2019-08-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0006_botinstance_raid_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatistics',
            name='days_since_install',
            field=models.CharField(blank=True, help_text='How many days since the game has been installed.', max_length=255, null=True, verbose_name='Days Since Install'),
        ),
    ]
