# Generated by Django 2.1.7 on 2019-08-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0008_make_configuration_paranoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='next_break',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Break'),
        ),
        migrations.AddField(
            model_name='botinstance',
            name='resume_from_break',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resume From Break'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='breaks_jitter',
            field=models.PositiveIntegerField(default=40, help_text='Specify a jitter amount so that breaks take place at different intervals.', verbose_name='Breaks Jitter Amount'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='breaks_minutes_max',
            field=models.PositiveIntegerField(default=60, help_text='Maximum amount of minutes to break for.', verbose_name='Max Minutes For Break'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='breaks_minutes_min',
            field=models.PositiveIntegerField(default=20, help_text='Minimum amount of minutes to break for.', verbose_name='Min Minutes For Break'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='breaks_minutes_required',
            field=models.PositiveIntegerField(default=180, help_text='How many minutes of concurrent playtime is required before a break takes place.', verbose_name='Minutes Required Before Break Is Activated'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='enable_breaks',
            field=models.BooleanField(default=True, help_text='Enable the ability to take breaks in game.', verbose_name='Enable Breaks'),
        ),
    ]
