# Generated by Django 2.1.7 on 2019-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0009_breaks_bot_instance_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='default', help_text='Determine the name of the theme that will be activated on the dashboard.', max_length=255, verbose_name='Theme')),
            ],
            options={
                'verbose_name': 'Theme Config',
                'verbose_name_plural': "Theme Config's",
            },
        ),
    ]
