# Generated by Django 2.1.7 on 2019-08-24 18:27

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0010_themeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='window',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Current Window'),
        ),
    ]
