# Generated by Django 2.1.7 on 2019-08-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0011_botinstance_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactowned',
            name='instance',
            field=models.ForeignKey(help_text='The bot instance associated with this owned artifact.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='artifactstatistics',
            name='instance',
            field=models.ForeignKey(help_text='The bot instance associated with these artifact statistics.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='botinstance',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the bot instance.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='botstatistics',
            name='instance',
            field=models.ForeignKey(help_text='The bot instance associated with these game statistics.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='gamestatistics',
            name='instance',
            field=models.ForeignKey(help_text='The bot instance associated with these game statistics.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='prestige',
            name='instance',
            field=models.ForeignKey(help_text='The bot instance associated with this prestige.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='prestigestatistics',
            name='instance',
            field=models.ForeignKey(help_text='The bot instance associated with these prestige statistics.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='queue',
            name='instance',
            field=models.ForeignKey(help_text='The bot instance associated with this queued function.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='raidresult',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
        migrations.AddField(
            model_name='session',
            name='instance',
            field=models.ForeignKey(blank=True, help_text='The bot instance associated with the session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_instance', to='titandash.BotInstance', verbose_name='Session Instance'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='instance',
            field=models.ForeignKey(help_text='The bot instance associated with these statistics.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.BotInstance', verbose_name='Instance'),
        ),
    ]
