# Generated by Django 2.1.7 on 2019-09-15 14:27

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0012_multiple_session_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='configuration_snapshot',
            field=jsonfield.fields.JSONField(blank=True, help_text='Config snapshot used when session was started.', null=True, verbose_name='Configuration Snapshot'),
        ),
    ]
