# Generated by Django 2.1.7 on 2019-09-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0013_session_configuration_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='upgrade_owned_artifacts',
        ),
        migrations.AlterField(
            model_name='prestige',
            name='artifact',
            field=models.ForeignKey(blank=True, help_text='The artifact upgraded following this prestige.', null=True, on_delete=django.db.models.deletion.CASCADE, to='titandash.Artifact', verbose_name='Artifact Upgraded'),
        ),
    ]
