# Generated by Django 2.2.5 on 2019-10-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0014_artifact_toggle_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_artifact_discover_enchant',
            field=models.BooleanField(default=True, help_text='Enable the ability to discover or enchant artifacts if possible after a prestige.', verbose_name='Enable Artifact Discover/Enchant'),
        ),
    ]
