# Generated by Django 2.2.5 on 2019-10-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0016_rename_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='bottom_artifact',
        ),
    ]
