# Generated by Django 2.2.5 on 2019-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0018_milestone_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='next_milestone_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Milestone Check'),
        ),
    ]
