# Generated by Django 2.1.7 on 2019-10-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0019_botinstance_next_milestone_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='milestones_check_every_x_hours',
            field=models.PositiveIntegerField(default=1, help_text='Determine how many hours between each milestone check.', verbose_name='Check Milestones Every X Hours'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='milestones_check_on_start',
            field=models.BooleanField(default=False, help_text='Should milestones be checked for when a session is started?', verbose_name='Check Milestones On Session Start'),
        ),
    ]
