# Generated by Django 2.2.5 on 2019-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0024_configuration_master_level_only_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='next_randomized_prestige',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Randomized Prestige'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='enable_prestige_threshold_randomization',
            field=models.BooleanField(default=True, help_text='Enable the ability to add additional time to a prestige once one of the thresholds below are reached. For example, if this setting is enabled and you choose to prestige every 30 minutes, the actual prestige may take place in 33 minutes depending on the settings below. Additionally, if you choose to prestige at a percent, once you reach your percentage, the bot will wait the calculated amount of time before prestiging.', verbose_name='Enable Prestige Threshold Randomization'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='prestige_random_max_time',
            field=models.PositiveIntegerField(default=8, help_text='Specify the upper ceiling that will be used when calculating an amount of time to wait after a prestige threshold is reached.', verbose_name='Prestige Threshold Random Max Time'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='prestige_random_min_time',
            field=models.PositiveIntegerField(default=2, help_text='Specify the lower floor that will be used when calculating an amount of time to wait after a prestige threshold is reached.', verbose_name='Prestige Threshold Random Min Time'),
        ),
    ]
