# Generated by Django 2.2.5 on 2019-10-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0027_actions_upgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botinstance',
            name='next_recovery_reset',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='recovery_allowed_failures',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='recovery_check_interval_minutes',
        ),
    ]
