# Generated by Django 2.2.5 on 2019-10-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0028_remove_recovery_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='enable_ad_collection',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='enable_premium_ad_collect',
        ),
    ]
