# Generated by Django 2.2.5 on 2019-10-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0029_remove_ad_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='next_miscellaneous_actions',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Miscellaneous Actions'),
        ),
    ]
