# Generated by Django 2.2.5 on 2019-10-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0030_botinstance_next_miscellaneous_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='minigames_repeat',
            field=models.PositiveIntegerField(default=1, help_text='Specify how many times the minigames loop should run when executed.', verbose_name='Repeat Minigames'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tapping_repeat',
            field=models.PositiveIntegerField(default=1, help_text='Specify how many times the tapping loop should run when executed.', verbose_name='Repeat Tapping'),
        ),
    ]
