# Generated by Django 2.2.5 on 2019-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0031_repeats_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='shortcuts',
            field=models.BooleanField(blank=True, null=True, verbose_name='Enable Shortcuts'),
        ),
    ]
