# Generated by Django 2.2.5 on 2019-11-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0032_botinstance_shortcuts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='emulator',
        ),
    ]
