# Generated by Django 2.2.8 on 2019-12-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0034_add_perk_usage_to_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failsafe_settings', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', help_text='Enable or disable the failsafe functionality when a bot session is running. Note that turning this setting off may make it difficult to kill a bot session if an unrecoverable failure occurs. You can always force quit the application if needed though.', max_length=255, verbose_name='Failsafe Settings')),
                ('event_settings', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', help_text='Enable or disable the different functionality depending on whether or not an event is currently running in game that modifies in game locations.', max_length=255, verbose_name='In Game Event Settings')),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
