# Generated by Django 2.2.8 on 2019-12-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0035_globalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='enable_artifact_purchase',
            field=models.BooleanField(default=True, help_text='Enable the ability to purchase and upgrade discovered artifacts in game after a prestige has taken place.', verbose_name='Enable Artifact Purchase'),
        ),
    ]
