# Generated by Django 2.2.8 on 2020-01-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0037_globalsettings_pihole_ads_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_mega_boost',
            field=models.BooleanField(default=False, help_text='Enable the mega boost perk. This perk can only be collected if vip or pihole ads are enabled.', verbose_name='Enable Mega Boost'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='use_perk_on_prestige',
            field=models.CharField(choices=[('none', 'None'), ('mega_boost', 'Mega Boost'), ('power_of_swiping', 'Power Of Swiping'), ('adrenaline_rush', 'Adrenaline Rush'), ('make_it_rain', 'Make It Rain'), ('mana_potion', 'Mana Potion'), ('doom', 'Doom'), ('clan_crate', 'Clan Crate')], default='none', help_text='Choose a specific perk that you would like to use or purchase (if enabled) when a prestige occurs.', max_length=255, verbose_name='Use Perk On Prestige'),
        ),
    ]
