# Generated by Django 2.2.8 on 2020-01-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0038_add_mega_boost_perk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='enable_logging',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='logging_level',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='logging_level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Choose a logging level that will be used by bot sessions when they are running.', max_length=255, verbose_name='Logging Level'),
        ),
    ]
