# Generated by Django 2.2.8 on 2020-01-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0039_move_logging_settings_to_globals'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_headgear_swap',
            field=models.BooleanField(default=False, help_text='Enable the ability to swap headgear in game based on the most recently parsed hero. This setting requires that you have locked the headgear you wish to use. The first one found of the newest heroes type will be equipped.', verbose_name='Enable Headgear Swap'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='headgear_swap_every_x_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Specify the amount of seconds to wait in between each headgear swap process.', verbose_name='Swap Headgear Every X Seconds'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='headgear_swap_on_start',
            field=models.BooleanField(default=False, help_text='Should a headgear swap be initiated when a session is started.', verbose_name='Headgear Swap On Session Start'),
        ),
    ]
