# Generated by Django 2.2.8 on 2020-01-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0040_add_headgear_swap_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinstance',
            name='next_headgear_swap',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Headgear Swap'),
        ),
    ]
