# Generated by Django 2.2.10 on 2020-04-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0044_globalsettings_welcome_screen_checks_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='rate_screen_checks_settings',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', help_text='Enable or disable the option to check for the rate screen while a bot is running (turning this off may improve performance if you no longer get prompted to rate the game anymore).', max_length=255, verbose_name='Enable Rate Screen Checks'),
        ),
    ]
