# Generated by Django 2.2.5 on 2019-10-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='Version')),
                ('grabbed', models.BooleanField(default=False, verbose_name='Grabbed')),
            ],
            options={
                'verbose_name': 'Release Info',
                'verbose_name_plural': "Release Info's",
            },
        ),
    ]
