# Generated by Django 2.2.10 on 2020-04-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titanbootstrap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsettings',
            name='tesseract_directory',
        ),
    ]
